document.write('<link rel="stylesheet" type="text/css" href="MinsaPayDesignSystem.css">');
document.write('<meta name="viewport" content="width=device-width, initial-scale=1.0">');

document.write('<link rel="apple-touch-icon" sizes="57x57" href="/image/apple-icon-57x57.png">');
document.write('<link rel="apple-touch-icon" sizes="60x60" href="/image/apple-icon-60x60.png">');
document.write('<link rel="apple-touch-icon" sizes="72x72" href="/image/apple-icon-72x72.png">');
document.write('<link rel="apple-touch-icon" sizes="76x76" href="/image/apple-icon-76x76.png">');
document.write('<link rel="apple-touch-icon" sizes="114x114" href="/image/apple-icon-114x114.png">');
document.write('<link rel="apple-touch-icon" sizes="120x120" href="/image/apple-icon-120x120.png">');
document.write('<link rel="apple-touch-icon" sizes="144x144" href="/image/apple-icon-144x144.png">');
document.write('<link rel="apple-touch-icon" sizes="152x152" href="/image/apple-icon-152x152.png">');
document.write('<link rel="apple-touch-icon" sizes="180x180" href="/image/apple-icon-180x180.png">');
document.write('<link rel="icon" type="image/png" sizes="192x192"  href="/image/android-icon-192x192.png">');
document.write('<link rel="icon" type="image/png" sizes="32x32" href="/image/favicon-32x32.png">');
document.write('<link rel="icon" type="image/png" sizes="96x96" href="/image/favicon-96x96.png">');
document.write('<link rel="icon" type="image/png" sizes="16x16" href="/image/favicon-16x16.png">');
document.write('<link rel="manifest" href="/image/manifest.json">');
document.write('<meta name="msapplication-TileColor" content="#ffffff">');
document.write('<meta name="msapplication-TileImage" content="/image/ms-icon-144x144.png">');
document.write('<meta name="theme-color" content="#ffffff">');